version: '3.3'
services:
  inference:
    image: tensorflow/serving
    ports:
      - '8501:8501'
    volumes:
      - ./models:/usr/src/models
    command:
      - '--model_config_file=/usr/src/models/models.config'
      - '--model_config_file_poll_wait_seconds=60'

  gateway:
    build:
      context: gateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./gateway:/usr/src/app
      - ./models:/usr/src/models
    depends_on:
      - data-preprocessing
    networks:
      default:
        aliases:
          - gateway

  data-preprocessing:
    build:
      context: data_preprocessing
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    # this is just a way to detect changes when in dev
    volumes:
      - ./data_preprocessing:/usr/src/app
    networks:
      default:
        aliases:
          - data-preprocessing